
import eshaPhoto from './assets/my-photo.jpg';
import waseemPhoto from './assets/waseem .jpg';
import haseebPhoto from './assets/haseeb.jpg';
import samiPhoto from './assets/sami.jpg';

export const services = [
  {
    id: 'strategy-consulting',
    icon: 'trendingUp',
    img: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=80',
    title: 'Strategy Consulting',
    short: 'Data-driven strategies to accelerate business growth.',
    description:
      'We help you define a clear roadmap for growth by analyzing markets, competitors, and internal capabilities. Our strategy engagements turn ambiguity into an actionable, prioritized plan.',
    points: [
      'Market & competitor analysis',
      'Growth roadmap design',
      'KPI & performance frameworks',
      'Business model innovation',
    ],
  },
  {
    id: 'financial-advisory',
    icon: 'dollarSign',
    img: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
    title: 'Financial Advisory',
    short: 'Optimize capital structure and improve profitability.',
    description:
      'Our financial advisory practice helps organizations strengthen their balance sheets, raise capital, and improve profitability through rigorous financial modeling and risk assessment.',
    points: [
      'Financial modeling & forecasting',
      'Capital raising support',
      'Risk & compliance assessment',
      'Cost optimization',
    ],
  },
  {
    id: 'digital-transformation',
    icon: 'monitor',
    img: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
    title: 'Digital Transformation',
    short: 'Modernize operations with technology-first thinking.',
    description:
      'We guide organizations through digital transformation — from process automation to full technology stack modernization — ensuring adoption sticks and ROI is measurable.',
    points: [
      'Process automation',
      'Technology stack modernization',
      'Change management',
      'Digital maturity assessment',
    ],
  },
  {
    id: 'hr-consulting',
    icon: 'users',
    img: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600&q=80',
    title: 'HR Consulting',
    short: 'Build high-performing teams and organizational structures.',
    description:
      'Our HR consulting services help you design organizational structures, improve talent acquisition, and build a culture that retains top performers.',
    points: [
      'Org design & restructuring',
      'Talent acquisition strategy',
      'Performance management systems',
      'Culture & engagement programs',
    ],
  },
  {
    id: 'marketing-strategy',
    icon: 'megaphone',
    img: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=600&q=80',
    title: 'Marketing Strategy',
    short: 'Position your brand and reach the right audience.',
    description:
      'We craft marketing strategies grounded in customer insight and data — helping you position your brand effectively and reach the audiences that matter most.',
    points: [
      'Brand positioning',
      'Customer segmentation',
      'Campaign strategy & analytics',
      'Go-to-market planning',
    ],
  },
  {
    id: 'risk-management',
    icon: 'shield',
    img: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80',
    title: 'Risk Management',
    short: 'Identify, assess, and mitigate business risks.',
    description:
      'We help organizations build robust risk management frameworks that identify vulnerabilities early and put mitigation strategies in place before they become costly problems.',
    points: [
      'Enterprise risk assessment',
      'Compliance frameworks',
      'Business continuity planning',
      'Crisis management support',
    ],
  },
];

export const portfolio = [
  {
    id: 'corporate-brand-strategy',
    title: 'Corporate Brand Strategy Overhaul',
    client: 'TechNova Solutions',
    category: 'Branding',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&q=80',
    description: 'A complete brand repositioning for a B2B SaaS company, resulting in 210% increase in qualified leads and a unified brand presence across 12 markets.',
    results: [
      '210% increase in qualified leads',
      '3x social media engagement rate',
      'Unified brand presence across 12 markets',
      '35% reduction in customer acquisition cost',
    ],
    challenge: 'TechNova Solutions had outgrown their original brand identity. With a fragmented visual presence across different product lines and markets, they needed a cohesive brand strategy that could scale globally while maintaining local relevance.',
    solution: 'We developed a comprehensive brand architecture, visual identity system, messaging framework, and rollout strategy. This included market research, stakeholder workshops, competitor analysis, and a phased implementation plan.',
    timeline: '6 months',
    testimonial: 'The team transformed our brand from a collection of disjointed logos into a powerful, unified identity that resonates across every touchpoint.',
    testimonialAuthor: 'Maria Chen, CMO',
    results_img: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80',
  },
  {
    id: 'digital-transformation-finance',
    title: 'Digital Transformation for Financial Services',
    client: 'Apex Financial Group',
    category: 'Digital Transformation',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&q=80',
    description: 'End-to-end digital transformation modernizing legacy systems, automating workflows, and launching a customer-facing digital platform.',
    results: [
      '60% reduction in processing time',
      '92% customer satisfaction score',
      '$4.2M annual operational savings',
      'Zero security incidents post-migration',
    ],
    challenge: 'Apex Financial Group was operating on legacy infrastructure that limited scalability, created security vulnerabilities, and delivered a poor customer experience compared to modern fintech competitors.',
    solution: 'We designed a cloud-native architecture, implemented automated workflows, deployed AI-powered fraud detection, and built an omnichannel customer platform with seamless integration to core banking systems.',
    timeline: '14 months',
    testimonial: 'This transformation didn\'t just modernize our technology — it redefined how we serve our customers and compete in the digital age.',
    testimonialAuthor: 'James Wright, CIO',
    results_img: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
  },
  {
    id: 'supply-chain-optimization',
    title: 'Global Supply Chain Optimization',
    client: 'OmniLogistix Inc.',
    category: 'Operations',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&q=80',
    description: 'Comprehensive supply chain redesign reducing costs by 28% while improving delivery times across 40+ countries.',
    results: [
      '28% reduction in logistics costs',
      '99.3% on-time delivery rate',
      '40% inventory turnover improvement',
      'Carbon footprint reduced by 22%',
    ],
    challenge: 'OmniLogistix faced rising logistics costs, inventory inefficiencies, and increasing customer demands for faster, more sustainable delivery options across their global operations.',
    solution: 'We redesigned the supply chain network, implemented AI-driven demand forecasting, optimized warehouse locations, and introduced sustainable packaging and routing solutions.',
    timeline: '10 months',
    testimonial: 'Our supply chain went from a cost center to a competitive advantage. The ROI exceeded our projections by 40%.',
    testimonialAuthor: 'Robert Kim, COO',
    results_img: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&q=80',
  },
  {
    id: 'market-expansion-strategy',
    title: 'Market Expansion into APAC',
    client: 'GreenLeaf Energy',
    category: 'Strategy',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&q=80',
    description: 'Strategic market entry and expansion plan for a renewable energy company entering 5 Asian markets simultaneously.',
    results: [
      '$180M revenue in first 2 years',
      '5 markets successfully entered',
      '45 strategic partnerships formed',
      '#1 market position in 2 countries',
    ],
    challenge: 'GreenLeaf Energy needed to rapidly expand into Asian markets but faced regulatory complexity, cultural barriers, and a fragmented competitive landscape across multiple countries.',
    solution: 'We developed a phased market entry strategy, conducted in-depth local market research, established partnership frameworks, and built a localization roadmap for products and messaging.',
    timeline: '18 months',
    testimonial: 'Their deep understanding of local markets and regulatory landscapes was instrumental to our successful expansion.',
    testimonialAuthor: 'Dr. Sarah Park, CEO',
    results_img: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80',
  },
  {
    id: 'hr-transformation-tech',
    title: 'HR Transformation for Tech Scale-up',
    client: 'CodeBridge Systems',
    category: 'HR Consulting',
    image: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400&q=80',
    description: 'Scaled the HR organization from 200 to 2,000 employees with modern people operations, culture frameworks, and talent systems.',
    results: [
      '400% workforce growth supported',
      'Employee NPS improved from 32 to 78',
      '82% reduction in time-to-hire',
      'Top 5 employer brand in sector',
    ],
    challenge: 'CodeBridge Systems was growing at 200% year-over-year but their HR infrastructure couldn\'t keep up — leading to culture dilution, hiring bottlenecks, and rising attrition.',
    solution: 'We built scalable HR processes, implemented an integrated HRIS, designed a career progression framework, and created a data-driven talent acquisition engine.',
    timeline: '8 months',
    testimonial: 'They didn\'t just fix our HR problems — they built the foundation for our culture to scale without breaking.',
    testimonialAuthor: 'Alex Rivera, VP People',
    results_img: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600&q=80',
  },
  {
    id: 'financial-restructuring',
    title: 'Financial Restructuring & Turnaround',
    client: 'Heritage Manufacturing Co.',
    category: 'Financial Advisory',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&q=80',
    description: 'Complete financial restructuring that saved 1,200 jobs and returned the company to profitability within 12 months.',
    results: [
      'Company returned to profitability in 12 months',
      '1,200 jobs preserved',
      'Debt reduced by 65%',
      'EBITDA margin improved from -8% to +14%',
    ],
    challenge: 'Heritage Manufacturing was on the brink of bankruptcy with declining revenues, unsustainable debt levels, and operational inefficiencies across their production facilities.',
    solution: 'We led a comprehensive restructuring including debt negotiation, operational cost optimization, product portfolio rationalization, and a new financial governance framework.',
    timeline: '12 months',
    testimonial: 'They gave us a second chance. The restructuring saved our company and our people\'s livelihoods.',
    testimonialAuthor: 'Thomas Baker, Chairman',
    results_img: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
  },
];

export const team = [
  {
    name: 'Esha Javed',
    role: 'Founder & CEO',
    img: eshaPhoto,
  },
  {
    name: 'Waseem Manzoor',
    role: 'Head of Strategy',
    img: waseemPhoto,
  },
  {
    name: 'Abdul Haseeb',
    role: 'Financial Advisor',
    img: haseebPhoto,
  },
  {
    name: 'Abdul Sami',
    role: 'Head of Technology',
    img: samiPhoto,
  },
];
